#!/bin/bash

function MkIni {
  mkdir -p /tmp/cdm-$3

  (
    echo "environment        = \"cdm-hello-world\""
    echo "agent              = \"cdm-$3\""
    echo "work_folder        = \"/tmp/cdm-$3\""
    echo "latex              = \"test\""
    echo ""
    echo "[ftp]"
    echo "user               = \"modelling_bus\""
    echo "password           = \"Geheim1967\""
    echo "port               = 21"
    echo "server             = \"$2\""
    echo "single_server_mode = $4"
    echo "active_transfers   = $5"
    echo "prefix             = \"modelling_bus\""
    echo ""
    echo "[mqtt]"
    echo "user               = \"modelling_bus\""
    echo "password           = \"Geheim1967\""
    echo "port               = 1883"
    echo "broker             = \"$2\""
    echo "prefix             = \"modelling_bus\""
    echo "load_delay         = 10"
  ) > $1.ini
}

for m in *; do
  if [ -d "$m" ]; then
    MkIni $m/config   localhost               tester false false
    MkIni $m/home     frame.fritz.box         tester false false
    MkIni $m/tuwien   dm-lab.big.tuwien.ac.at tester false true
  fi
done
