#!/bin/bash

function MkIni {
  mkdir -p /tmp/$3

  (
    echo "environment        = \"cdm-hello-world\""
    echo "agent              = \"$3\""
    echo "work_folder        = \"/tmp/$3\""
    echo "latex              = \"test\""
    echo ""
    echo "[ftp]"
    echo "user               = \"modelling_bus\""
    echo "password           = \"Geheim1967\""
    echo "port               = 21"
    echo "server             = \"$2\""
    echo "single_server_mode = $4"
    echo "active_transfers   = $5"
    echo "prefix             = \"modelling_bus\""
    echo ""
    echo "[mqtt]"
    echo "user               = \"modelling_bus\""
    echo "password           = \"Geheim1967\""
    echo "port               = 1883"
    echo "broker             = \"$2\""
    echo "prefix             = \"modelling_bus\""
    echo "load_delay         = 10"
  ) > $1.ini
}

function MkInis {
  MkIni $1/config   localhost               $2 false false
  MkIni $1/home     frame.fritz.box         $2 false false
  MkIni $1/tuwien   dm-lab.big.tuwien.ac.at $2 false true
}

for m in *; do
  if [ -d "$m" ]; then
    rm $m/*.ini 2> /dev/null
  fi
done

MkInis cdm_pdf_renderer cdm_renderer
MkInis cdm_test_poster  cdm_poster
MkInis mbus_delete      mbus_deleter
MkInis mbus_get         mbus_getter
MkInis mbus_post        mbus_poster
MkInis mbus_listen      mbus_listener